autoInstallPeers: true

dedupePeerDependents: true

engineStrict: true

onlyBuiltDependencies:
 - sharp
 - unrs-resolver

packageImportMethod: hardlink

preferFrozenLockfile: true

sideEffectsCache: true

storeDir: ~/.pnpm-store

updateConfig:
 ignoreDependencies:
  - eslint
  - '@eslint/js'
